// Generated by scripts/promo/render-mcp-demo.ts from q*.jsonl. Do not edit.
window.TRANSCRIPT = [
  {
    "question": "How did my websites do last week?",
    "steps": [
      {
        "tool": "list_environments",
        "args": "",
        "gist": "demo (admin, works)"
      },
      {
        "tool": "list_websites",
        "args": "",
        "gist": "Paperkite: Blog, Documentation, Marketing site"
      },
      {
        "tool": "compare_periods",
        "args": "project: \"paperkite\", preset: \"last_7_days\"",
        "gist": "Paperkite (all websites): 24,163 page views (+45.5%), 12,534 visitors (+70.7%) vs the period before"
      },
      {
        "tool": "get_traffic_overview",
        "args": "project: \"paperkite\", preset: \"last_7_days\", website: \"site-blog\"",
        "gist": "Blog, 09-21 to 09-28: 2,228 page views, 1,286 visitors"
      },
      {
        "tool": "get_traffic_overview",
        "args": "project: \"paperkite\", preset: \"last_7_days\", website: \"site-docs\"",
        "gist": "Documentation, 09-21 to 09-28: 5,080 page views, 1,701 visitors"
      },
      {
        "tool": "get_traffic_overview",
        "args": "project: \"paperkite\", preset: \"last_7_days\", website: \"site-marketing\"",
        "gist": "Marketing site, 09-21 to 09-28: 16,855 page views, 9,547 visitors"
      }
    ],
    "answer": "Environment: demo (Paperkite project), last 7 days, 2026-09-21 23:37 to 2026-09-28 23:37 UTC.\n\n- **Overall:** 24,163 page views (+45.5%) and 12,534 unique visitors (+70.7%) versus the previous week.\n- **Marketing site:** 16,855 views, driven by a spike on Sep 24–25 (7,801 views on Sep 24). Hacker News sent 8,551 of those views.\n- **Documentation:** 5,080 views, steady on weekdays and about half that on the weekend. Top pages were /getting-started and /install.\n- **Blog:** 2,228 views, flat day to day. Blog pages fell 34–63% week over week, including /posts/shipping-offline-first (−63%)."
  },
  {
    "question": "Why did traffic to the blog drop?",
    "steps": [
      {
        "tool": "compare_periods",
        "args": "project: \"paperkite\", website: \"site-blog\", preset: \"last_7_days\"",
        "gist": "Blog: 2,228 page views (-34.2%), 1,286 visitors (-33.5%) vs the period before"
      },
      {
        "tool": "get_traffic_overview",
        "args": "project: \"paperkite\", website: \"site-blog\", start: \"2026-09-14T23:37:00Z\", end: \"2026-09-21T23:37:00Z\"",
        "gist": "Blog, 09-14 to 09-21: 3,387 page views, 1,935 visitors"
      }
    ],
    "answer": "Environment: demo, Blog website (Paperkite project), 2026-09-21 to 2026-09-28 UTC compared with the week before.\n\n- **Size of the drop:** Page views fell from 3,387 to 2,228 (−34.2%). Visitors fell from 1,935 to 1,286 (−33.5%).\n- **Likely cause:** A referrer, inkwell-weekly.example, sent 1,138 views the previous week and doesn't appear in this week's top referrers. Its traffic looks like a one-off mention that has ended.\n- **Where it shows:** /posts/shipping-offline-first fell 1,034 → 379 (−63%). That accounts for about 655 of the 1,159 lost views. The blog home and /posts/kite-design-notes fell about 34% each.\n- **Baseline is steady:** Google, DuckDuckGo, Bing and internal referrals are flat. Other posts are within ±5%, so there's no sign of an SEO or tracking problem."
  }
];
