import { existsSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { type Ctx, OpsError, done, normalizeWorkerUrl, step, waitForHealth } from './context.js';
import {
  SECRETS,
  SECRET_KINDS,
  type SecretKind,
  formatSecretBlock,
  generateSecrets
} from './secrets.js';
import type { RunResult } from './terminal.js';

export type BackendOptions = {
  /** Undefined asks the operator, with a detected default. */
  firstRun?: boolean;
  worker: string;
  database: string;
  bucket: string;
};
export type BackendResult = {
  workerUrl: string;
  firstRun: boolean;
  configPath: string;
  /** Only secrets generated by this run; an update keeps the ones already on the Worker. */
  secrets: Record<string, string>;
};

export {
  DEFAULT_NAMES,
  assertResourceName,
  readConfigNames,
  parseAccounts,
  parseDatabases,
  parseBuckets,
  parseWorkerUrl,
  renderProductionConfig
} from '../../packages/ops-core/src/index.js';
import {
  assertResourceName,
  parseAccounts,
  parseBuckets,
  parseDatabases,
  parseWorkerUrl,
  readConfigNames,
  renderProductionConfig
} from '../../packages/ops-core/src/index.js';

const clean = (text: string): string => text.replace(/\u001b\[[0-9;]*m/g, '').trim();
const lastLines = (result: RunResult): string =>
  clean(`${result.stderr}\n${result.stdout}`).split('\n').filter(Boolean).slice(-6).join('\n');

/** Shows generated secrets once, makes the operator confirm they saved them, then wipes the screen. */
export async function presentSecrets(ctx: Ctx, secrets: Record<string, string>): Promise<void> {
  ctx.out(`\n${formatSecretBlock(secrets)}\n`);
  await ctx.prompt.typeToContinue('Type "saved" once they are in your password manager:', 'saved');
  ctx.clear();
  done(ctx, 'Secrets saved. They were cleared from this screen and are stored nowhere else.');
}

export async function setUpBackend(ctx: Ctx, options: BackendOptions): Promise<BackendResult> {
  const { worker, database, bucket } = options;
  for (const [kind, name] of [
    ['Worker', worker],
    ['Database', database],
    ['Bucket', bucket]
  ] as const)
    assertResourceName(kind, name);
  const env: Record<string, string> = {};
  const wr = (args: readonly string[], extra: Parameters<Ctx['run']>[1] = {}): Promise<RunResult> =>
    ctx.run(args, { ...extra, env });
  const deployDir = join(ctx.cwd, 'deploy', 'cloudflare');
  const configPath = join(deployDir, 'wrangler.production.toml');
  const configArgs = ['--config', configPath];

  step(ctx, 'Building Vizoalica…');
  const built = await ctx.build();
  if (!built.ok)
    throw new OpsError(`The build failed:\n${built.output.split('\n').slice(-12).join('\n')}`);

  step(ctx, 'Checking your Cloudflare login…');
  const whoami = async () => parseAccounts((await wr(['whoami'])).stdout);
  let accounts = await whoami();
  if (accounts.length === 0) {
    ctx.out('  A browser window will open so you can sign in to Cloudflare.');
    const login = await wr(['login'], { interactive: true });
    accounts = login.code === 0 ? await whoami() : [];
    if (accounts.length === 0)
      throw new OpsError('Cloudflare sign-in did not complete. Run the command again to retry.');
  }
  let account = accounts[0]!;
  if (accounts.length > 1) {
    accounts.forEach((item, index) => ctx.out(`  ${index + 1}) ${item.name}`));
    const choice = Number(
      await ctx.prompt.text('Which account should Vizoalica use? (number)', '1')
    );
    account = accounts[choice - 1] ?? accounts[0]!;
    env.CLOUDFLARE_ACCOUNT_ID = account.id;
  }
  done(ctx, `Cloudflare account: ${account.name}`);

  const databases = parseDatabases((await wr(['d1', 'list', '--json'])).stdout);
  const buckets = parseBuckets((await wr(['r2', 'bucket', 'list'])).stdout);
  const existingDatabase = databases.find((item) => item.name === database);
  const existingBucket = buckets.includes(bucket);
  const detected =
    existingDatabase || existingBucket
      ? 'existing Vizoalica resources found'
      : 'nothing installed yet';
  ctx.out(`  Detected: ${detected}.`);
  ctx.out(
    '  First install: creates a database, a storage bucket, and the Worker, and generates your secrets.'
  );
  ctx.out(
    '  Update: deploys this checkout over your existing install; your data and secrets are kept.'
  );
  const firstRun =
    options.firstRun ??
    (await ctx.prompt.confirm(
      'Is this the first install on this Cloudflare account?',
      !(existingDatabase || existingBucket)
    ));

  const result = firstRun ? await firstInstall() : await update();
  return result;

  async function deploy(): Promise<string> {
    step(ctx, 'Deploying the Worker…');
    const deployed = await wr(['deploy', ...configArgs], { interactive: true, echo: true });
    if (deployed.code !== 0) throw new OpsError(`The deploy failed:\n${lastLines(deployed)}`);
    const found = parseWorkerUrl(`${deployed.stdout}\n${deployed.stderr}`);
    const url =
      found ??
      (await ctx.prompt.text('Paste the Worker address shown above (https://….workers.dev)'));
    return normalizeWorkerUrl(url);
  }

  async function verifyHealth(workerUrl: string): Promise<void> {
    step(ctx, 'Checking the Worker is healthy…');
    if (await waitForHealth(ctx, workerUrl)) done(ctx, `Healthy: ${workerUrl}`);
    else
      ctx.out(
        `! ${workerUrl}/healthz did not answer yet. A brand-new workers.dev name can take a minute; try that URL again shortly.`
      );
  }

  async function ensureSecrets(): Promise<Record<string, string>> {
    const listed = await wr(['secret', 'list', '--format', 'json', ...configArgs]);
    const present = new Set(
      (() => {
        try {
          return (
            JSON.parse(listed.stdout.slice(listed.stdout.indexOf('['))) as Array<{ name: string }>
          ).map((item) => item.name);
        } catch {
          return [] as string[];
        }
      })()
    );
    const missing = SECRET_KINDS.filter((kind: SecretKind) => !present.has(SECRETS[kind].name));
    if (missing.length === 0) return {};
    step(
      ctx,
      `Generating ${missing.length === 3 ? 'your three secrets' : `${missing.length} missing secret(s)`}…`
    );
    const generated = generateSecrets(missing);
    const stored = await wr(['secret', 'bulk', ...configArgs], {
      stdin: JSON.stringify(generated)
    });
    if (stored.code !== 0) throw new OpsError(`Storing the secrets failed:\n${lastLines(stored)}`);
    done(ctx, 'Secrets stored on the Worker.');
    await presentSecrets(ctx, generated);
    return generated;
  }

  async function firstInstall(): Promise<BackendResult> {
    if (existingDatabase || existingBucket)
      throw new OpsError(
        `"${existingDatabase ? database : bucket}" already exists, so this is not a first install.\nAnswer "no" to update it, or pick new names with --database, --bucket, and --worker-name.`
      );
    if (existsSync(configPath)) {
      const backup = `${configPath}.bak-${Date.now()}`;
      renameSync(configPath, backup);
      ctx.out(`  Moved your old ${configPath} aside to ${backup}.`);
    }
    const created: string[] = [];
    try {
      step(ctx, `Creating the database "${database}"…`);
      const d1 = await wr(['d1', 'create', database], { stdin: '' });
      if (d1.code !== 0) throw new OpsError(`Creating the database failed:\n${lastLines(d1)}`);
      created.push(`d1:${database}`);
      const uuid = parseDatabases((await wr(['d1', 'list', '--json'])).stdout).find(
        (item) => item.name === database
      )?.uuid;
      if (!uuid) throw new OpsError('The database was created but its ID could not be read.');

      step(ctx, `Creating the storage bucket "${bucket}"…`);
      const r2 = await wr(['r2', 'bucket', 'create', bucket], { stdin: '' });
      if (r2.code !== 0)
        throw new OpsError(
          /enable|not.*enabled|10042/i.test(lastLines(r2))
            ? 'R2 is not enabled on this account. Open the Cloudflare dashboard → R2, activate it (billing details may be requested), then run this again.'
            : `Creating the bucket failed:\n${lastLines(r2)}`
        );
      created.push(`r2:${bucket}`);

      step(ctx, 'Writing deploy/cloudflare/wrangler.production.toml…');
      const example = readFileSync(join(deployDir, 'wrangler.example.toml'), 'utf8');
      writeFileSync(
        configPath,
        renderProductionConfig(example, { worker, database, databaseId: uuid, bucket }),
        { mode: 0o600 }
      );

      step(ctx, 'Creating the tables…');
      const migrated = await wr(
        ['d1', 'migrations', 'apply', database, '--remote', ...configArgs],
        { stdin: '' }
      );
      if (migrated.code !== 0)
        throw new OpsError(`Creating the tables failed:\n${lastLines(migrated)}`);
    } catch (error) {
      if (
        created.length > 0 &&
        (await ctx.prompt.confirm(
          'Remove the empty resources this run created, so you can retry cleanly?',
          true
        ))
      ) {
        for (const item of created.reverse()) {
          const [kind, name] = item.split(':') as [string, string];
          await wr(
            kind === 'd1' ? ['d1', 'delete', name, '-y'] : ['r2', 'bucket', 'delete', name],
            { stdin: '' }
          );
        }
        ctx.out('  Removed. Nothing is left behind.');
      }
      throw error;
    }
    const workerUrl = await deploy();
    const secrets = await ensureSecrets();
    await verifyHealth(workerUrl);
    return { workerUrl, firstRun: true, configPath, secrets };
  }

  async function update(): Promise<BackendResult> {
    if (!existingDatabase || !existingBucket)
      throw new OpsError(
        `There is nothing to update: "${existingDatabase ? bucket : database}" does not exist on this account.\nAnswer "yes" for a first install, or pass --database, --bucket, and --worker-name to point at your existing install.`
      );
    if (!existsSync(configPath)) {
      step(
        ctx,
        'Rebuilding deploy/cloudflare/wrangler.production.toml from your existing install…'
      );
      const example = readFileSync(join(deployDir, 'wrangler.example.toml'), 'utf8');
      writeFileSync(
        configPath,
        renderProductionConfig(example, {
          worker,
          database,
          databaseId: existingDatabase.uuid,
          bucket
        }),
        { mode: 0o600 }
      );
    } else {
      const names = readConfigNames(readFileSync(configPath, 'utf8'));
      if (
        names &&
        (names.database !== database || names.bucket !== bucket || names.worker !== worker)
      )
        throw new OpsError(
          `${configPath} points at "${names.worker}" / "${names.database}" / "${names.bucket}", not the names you asked for.\nRun again with those names (--worker-name, --database, --bucket) or move that file aside.`
        );
    }
    const workerUrl = await deploy();
    const secrets = await ensureSecrets();
    await verifyHealth(workerUrl);
    return { workerUrl, firstRun: false, configPath, secrets };
  }
}
